export const USER_CONSTRAINTS = {
  // USERNAME
  MIN_USERNAME_LENGTH: 8,
  MAX_USERNAME_LENGTH: 32,

  // PASSWORD
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 32,
  MIN_PASSWORD_UPPERCASE: 1,
  MIN_PASSWORD_NUMBER: 1,
  MIN_PASSWORD_SYMBOL: 1,

  // FIRST NAME
  MIN_FIRST_NAME_LENGTH: 2,
  MAX_FIRST_NAME_LENGTH: 50,

  // LAST NAME
  MIN_LAST_NAME_LENGTH: 3,
  MAX_LAST_NAME_LENGTH: 90,

  // BIO
  MIN_BIO_LENGTH: 0,
  MAX_BIO_LENGTH: 300,
} as const;
