export const USER_CONSTRAINTS = {
  // USERNAME
  MIN_USERNAME_LENGTH: 8,
  MAX_USERNAME_LENGTH: 32,

  // PASSWORD
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 32,
  MIN_PASSWORD_UPPERCASE: 1,
  MIN_PASSWORD_NUMBER: 1,
  MIN_PASSWORD_SYMBOL: 1,
} as const;
