export const USER_CONSTRAINTS = {
  // USERNAME
  MIN_USERNAME_LENGTH: 8,
  MAX_USERNAME_LENGTH: 32,
  USERNAME_PATTERN: /^[a-zA-z0-9_]+$/,

  // PASSWORD
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 32,
  MIN_PASSWORD_UPPERCASE: 1,
  MIN_PASSWORD_NUMBER: 1,
  MIN_PASSWORD_SYMBOL: 1,

  // FIRST NAME
  MIN_FIRST_NAME_LENGTH: 2,
  MAX_FIRST_NAME_LENGTH: 50,

  // LAST NAME
  MIN_LAST_NAME_LENGTH: 2,
  MAX_LAST_NAME_LENGTH: 90,

  // BIO
  MIN_BIO_LENGTH: 0,
  MAX_BIO_LENGTH: 300,

  NAME_PATTERN: /^[A-Za-zÀ-ÖØ-öø-ÿ' -]+$/,

  // AVATAR IMAGE
  AVATAR_IMAGE_ALLOWED_EXTENSIONS: ['.png', '.jpeg', '.jpg', '.webp'],
  MAX_SIZE_AVATAR_IMAGE: 1024 * 1024 * 10, // 10 MB
} as const;
