name: CI
run-name: ${{ github.actor }} is contributing to this pile of sh- 💩

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    # Add the database as a service container
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blogs_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://username:password@localhost:5432/blogs_db
      ACCESS_TOKEN_SECRET: 102j4102jas0f9j
      REFRESH_TOKEN_SECRET: 039j9309j3290j4
      HOST: localhost
      PORT: 3000

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install lsof
        run: sudo apt-get update && sudo apt-get install -y lsof

      - run: npm ci --legacy-peer-deps

      # Generate prisma client
      - run: |
          export DATABASE_URL=${{ env.DB_URL }}
          npx nx run @dans-coding-world/prisma-schema:generate-types:e2e

      - run: |
          export NODE_ENV=test
          npx nx run-many -t lint test build

      - run: |
          export NODE_ENV=test_e2e
          npx nx run-many -t e2e
