name: CI
run-name: ${{ github.actor }} is contributing to this pile of sh- 💩

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    # Add the database as a service container
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blogs_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://username:password@localhost:5432/blogs_db
      ACCESS_TOKEN_SECRET: 102j4102jas0f9j
      REFRESH_TOKEN_SECRET: 039j9309j3290j4
      API_HOST: localhost
      API_PORT: 3000
      VITE_PUBLIC_BLOG_HOST: localhost
      VITE_PUBLIC_BLOG_PORT: 4200
      VITE_ADMIN_BLOG_HOST: localhost
      VITE_ADMIN_BLOG_PORT: 5173

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install lsof
        run: sudo apt-get update && sudo apt-get install -y lsof

      - name: Install cypress dependencies
        run: sudo apt-get install -y libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb

      - run: PRISMA_CLI_BINARY_TARGETS=debian-openssl-3.0.x npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npm install -g playwright

      - name: Install Playwright Browsers-2
        run: npx playwright install --with-deps

      # Generate prisma client
      - run: |
          export DATABASE_URL=${{ env.DATABASE_URL }}
          npx nx run @dans-coding-world/prisma-schema:generate-types:e2e --skipNxCache

      - run: |
          npx nx build api --skipNxCache

      - name: Run Lint, Build and Tests
        run: |
          export NODE_ENV=test
          npx nx run-many -t lint build test --skipNxCache

      - name: Run Api E2E tests
        run: |
          export NODE_ENV=test_e2e
          npx nx e2e api-e2e

      - name: Run Public Blog E2E tests
        run: |
          export NODE_ENV=test_e2e
          npx nx e2e public-blog-e2e

      - name: Run Blog Admin E2E tests
        run: |
          export NODE_ENV=test_e2e
          npx nx e2e blog-admin-e2e
